### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by antagomir** [JuliaTurkuDataScience/PkgTutorial.jl#2]
Check is these are covered to some extent (at least a link to a relevant external tutorial, if nothing else):

    How to register a new Julia package
    How to check and build a Julia package after changes to make sure it works
    Where to find good instructions on the coding style and recommended practices in developing Julia packages
    How to add unit tests
    How to document new functions
    How to add new tutorial examples
    How to edit the package website
    How to add example data
    Anything else important?

**Comment by RiboRings** [comment]
I think I covered most of these points. If later you notice something's missing, just let me know.
